name: Weekly releases

on:
  repository_dispatch:
    types: manual-archlinux-devel-trigger
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * */7'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Docker Hub build
      run: 'curl -H "Content-Type: application/json" -X POST ${{ secrets.DOCKER_HUB_TRIGGER_URL }}'
